#############################################################################
# Makefile for building: monavpreprocessor
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Sep 3 15:47:57 2016
# Project:  monavpreprocessor.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile monavpreprocessor.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-preprocessor \
		sub-plugins-preprocessor_plugins-pro

preprocessor//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) preprocessor/ || $(MKDIR) preprocessor/ 
	cd preprocessor/ && $(QMAKE) /home/users/athan/OSM/tools/monav-0.3/preprocessor/preprocessor.pro -o $(MAKEFILE)
sub-preprocessor-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) preprocessor/ || $(MKDIR) preprocessor/ 
	cd preprocessor/ && $(QMAKE) /home/users/athan/OSM/tools/monav-0.3/preprocessor/preprocessor.pro -o $(MAKEFILE)
sub-preprocessor: preprocessor//$(MAKEFILE) sub-plugins-preprocessor_plugins-pro FORCE
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE)
sub-preprocessor-make_default: preprocessor//$(MAKEFILE) sub-plugins-preprocessor_plugins-pro-make_default FORCE
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE) 
sub-preprocessor-make_first: preprocessor//$(MAKEFILE) sub-plugins-preprocessor_plugins-pro-make_first FORCE
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE) first
sub-preprocessor-all: preprocessor//$(MAKEFILE) sub-plugins-preprocessor_plugins-pro-all FORCE
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE) all
sub-preprocessor-clean: preprocessor//$(MAKEFILE) sub-plugins-preprocessor_plugins-pro-clean FORCE
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE) clean
sub-preprocessor-distclean: preprocessor//$(MAKEFILE) sub-plugins-preprocessor_plugins-pro-distclean FORCE
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE) distclean
sub-preprocessor-install_subtargets: preprocessor//$(MAKEFILE) sub-plugins-preprocessor_plugins-pro-install_subtargets FORCE
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE) install
sub-preprocessor-uninstall_subtargets: preprocessor//$(MAKEFILE) sub-plugins-preprocessor_plugins-pro-uninstall_subtargets FORCE
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE) uninstall
plugins//$(MAKEFILE).preprocessor_plugins: 
	@$(CHK_DIR_EXISTS) plugins/ || $(MKDIR) plugins/ 
	cd plugins/ && $(QMAKE) /home/users/athan/OSM/tools/monav-0.3/plugins/preprocessor_plugins.pro -o $(MAKEFILE).preprocessor_plugins
sub-plugins-preprocessor_plugins-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugins/ || $(MKDIR) plugins/ 
	cd plugins/ && $(QMAKE) /home/users/athan/OSM/tools/monav-0.3/plugins/preprocessor_plugins.pro -o $(MAKEFILE).preprocessor_plugins
sub-plugins-preprocessor_plugins-pro: plugins//$(MAKEFILE).preprocessor_plugins FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins
sub-plugins-preprocessor_plugins-pro-make_default: plugins//$(MAKEFILE).preprocessor_plugins FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins 
sub-plugins-preprocessor_plugins-pro-make_first: plugins//$(MAKEFILE).preprocessor_plugins FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins first
sub-plugins-preprocessor_plugins-pro-all: plugins//$(MAKEFILE).preprocessor_plugins FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins all
sub-plugins-preprocessor_plugins-pro-clean: plugins//$(MAKEFILE).preprocessor_plugins FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins clean
sub-plugins-preprocessor_plugins-pro-distclean: plugins//$(MAKEFILE).preprocessor_plugins FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins distclean
sub-plugins-preprocessor_plugins-pro-install_subtargets: plugins//$(MAKEFILE).preprocessor_plugins FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins install
sub-plugins-preprocessor_plugins-pro-uninstall_subtargets: plugins//$(MAKEFILE).preprocessor_plugins FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins uninstall

Makefile: monavpreprocessor.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile monavpreprocessor.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile monavpreprocessor.pro

qmake_all: sub-preprocessor-qmake_all sub-plugins-preprocessor_plugins-pro-qmake_all FORCE

make_default: sub-preprocessor-make_default sub-plugins-preprocessor_plugins-pro-make_default FORCE
make_first: sub-preprocessor-make_first sub-plugins-preprocessor_plugins-pro-make_first FORCE
all: sub-preprocessor-all sub-plugins-preprocessor_plugins-pro-all FORCE
clean: sub-preprocessor-clean sub-plugins-preprocessor_plugins-pro-clean FORCE
distclean: sub-preprocessor-distclean sub-plugins-preprocessor_plugins-pro-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-preprocessor-install_subtargets sub-plugins-preprocessor_plugins-pro-install_subtargets FORCE
uninstall_subtargets: sub-preprocessor-uninstall_subtargets sub-plugins-preprocessor_plugins-pro-uninstall_subtargets FORCE

sub-preprocessor-check: preprocessor/$(MAKEFILE) sub-plugins-preprocessor_plugins-pro-check
	cd preprocessor/ && $(MAKE) -f $(MAKEFILE) check
sub-plugins-preprocessor_plugins-pro-check: plugins/$(MAKEFILE).preprocessor_plugins
	cd plugins/ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins check
check: sub-preprocessor-check sub-plugins-preprocessor_plugins-pro-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

